### ISSUE TITLE
KeyError: Zlevel when importing parquet file generated from baysor polygon geojson

### ISSUE THREAD

**Issue by paularstrpo** [Vizgen/vizgen-postprocessing#27]
Hi! Thanks for making this tool available. I am trying to import segmentation polygons generated from baysor v0.6.2 using the docker container through singularity on my HPC. I was able to succesfully convert the geojson file to parquet with `vpt convert-geometry`:

```
## singularity pull docker://vzgdocker/vpt
VPT="/my/path/to/vpt_latest.sif"

singularity run $VPT vpt convert-geometry --overwrite --input-boundaries "region_0*baysor*polygons.json" --output-boundaries region_0_baysor_polygons.parquet 
```

However when I feed this parquet file into vpt update-vzg as follows, I get an error. 

My command:
```
singularity run $VPT vpt update-vzg --input-vzg my_sample_region_0.vzg --output-vzg my_sample_region_0_BAYSOR.vzg --input-boundaries region_0_baysor_polygons.parquet --input-entity-by-gene cell_by_gene_baysor.csv
```
The error:
```
Traceback (most recent call last):
  File "/vizgen_postprocessing/src/vpt/vizgen_postprocess.py", line 58, in main
    c.run(run_command, subparser_name, parsed)
  File "/vizgen_postprocessing/src/vpt/app/context.py", line 100, in run
    proc(*args)
  File "/vizgen_postprocessing/src/vpt/vizgen_postprocess.py", line 22, in run_command
    get_cmd_entrypoint(cmd)(args)
  File "/vizgen_postprocessing/src/vpt/update_vzg/__init__.py", line 10, in run
    main_update_vzg(args)
  File "/vizgen_postprocessing/src/vpt/update_vzg/run_update_vzg.py", line 55, in main_update_vzg
    cells_reader: CellsReader = cell_reader_factory(args.input_boundaries)
  File "/vizgen_postprocessing/src/vpt/utils/cellsreader.py", line 104, in cell_reader_factory
    return CellsGeoReader(data)
  File "/vizgen_postprocessing/src/vpt/utils/cellsreader.py", line 51, in __init__
    zLevels = data['ZLevel'].unique()
  File "/usr/local/lib/python3.10/dist-packages/geopandas/geodataframe.py", line 1415, in __getitem__
    result = super().__getitem__(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'ZLevel'
```

I am wondering if you could help me narrow down:
- whether this is an issue from the parquet conversion, and how I might be able to fix it,
- or if this is an issue with how Baysor formats the output geojson (in which case I'll cross-post this to the baysor repository)

I also noticed that Baysor seems to treat the z level as a continuous numeric, so there are z-levels with decimals (e.g. 1.2 etc). Could this be related? If so, do you have plans to add compatibility for this case during the parquet conversion to force the polygons into the nearest whole integer z-plane? 

Any guidance or help in getting these polygons into the vzg file would be greatly appreciated!

**Comment by paularstrpo** [comment]
I managed to fix this on my own, closing the issue

**Comment by pakiessling** [comment]
Hi @paularstrpo did you manage to transfer the Baysor segmentation to the .vzg?

I was able to create a .parquet like this https://github.com/pakiessling/baysor2vpt/blob/main/baysor2vizgen.py
but the resulting .vzg did not have any polygons :(
