### ISSUE TITLE
ValueError: Expected columns {'gene', 'global_z', 'global_x', 'global_y'} were not found in the input-transcripts file.

### ISSUE THREAD

**Issue by mbernste** [Vizgen/vizgen-postprocessing#7]
Hi,

When I attempt to assign transcripts to cells via the `partition-transcripts` option, I receive an error that the entity metadata file is missing certain columns: `{'gene', 'global_z', 'global_x', 'global_y'}`. Specifically, I run the following command:

`vpt partition-transcripts --input-boundaries ./results/cellpose_micron_space.parquet  --input-transcripts entity_metadata.csv --output-entity-by-gene entity_by_gene.csv`

And get the following error:

```
Details:
Expected columns {'gene', 'global_z', 'global_x', 'global_y'} were not found in the input-transcripts file. Input transcript file contained columns: ['EntityID', 'fov', 'volume', 'center_x', 'center_y', 'min_x', 'min_y', 'max_x', 'max_y', 'anisotropy', 'transcript_count', 'perimeter_area_ratio', 'solidity']
Traceback (most recent call last):
  File "/mnt/disks/scratch/mbernstein/miniconda3/vizgen_vpt/lib/python3.10/site-packages/vpt/vizgen_postprocess.py", line 58, in main
    c.run(run_command, subparser_name, parsed)
  File "/mnt/disks/scratch/mbernstein/miniconda3/vizgen_vpt/lib/python3.10/site-packages/vpt/app/context.py", line 100, in run
    proc(*args)
  File "/mnt/disks/scratch/mbernstein/miniconda3/vizgen_vpt/lib/python3.10/site-packages/vpt/vizgen_postprocess.py", line 22, in run_command
    get_cmd_entrypoint(cmd)(args)
  File "/mnt/disks/scratch/mbernstein/miniconda3/vizgen_vpt/lib/python3.10/site-packages/vpt/partition_transcripts/__init__.py", line 10, in run
    main_partition_transcripts(args)
  File "/mnt/disks/scratch/mbernstein/miniconda3/vizgen_vpt/lib/python3.10/site-packages/vpt/partition_transcripts/run_partition_transcripts.py", line 18, in main_partition_transcripts
    validate_args(args)
  File "/mnt/disks/scratch/mbernstein/miniconda3/vizgen_vpt/lib/python3.10/site-packages/vpt/partition_transcripts/cmd_args.py", line 35, in validate_args
    raise ValueError(f'Expected columns {transcripts_header.difference(header)} were not found in the '
ValueError: Expected columns {'gene', 'global_z', 'global_x', 'global_y'} were not found in the input-transcripts file. Input transcript file contained columns: ['EntityID', 'fov', 'volume', 'center_x', 'center_y', 'min_x', 'min_y', 'max_x', 'max_y', 'anisotropy', 'transcript_count', 'perimeter_area_ratio', 'solidity']
```

The entity metadata file indeed does not contain these columns. The command I used to generate the entity metadata file was:

`vpt derive-entity-metadata --input-boundaries results/cellpose_micron_space.parquet --output-metadata entity_metadata.csv`

Do you know how I can go about fixing this?

Thank you so much for your help!

Best,
Matt

**Comment by timwiggin** [comment]
Hi Matt, 

Thanks for including a copy of the command you ran! The `--input-transcripts` file should be the detected_transcripts.csv file produced by the MERSCOPE Instrument Software, not the entity_metadata.csv file.

Best,

Tim

**Comment by mbernste** [comment]
Oh whoops, that would make sense. Thank you, it worked with the correct transcripts file.
